### ISSUE TITLE
handling css

### ISSUE THREAD

**Issue by joerupen** [dashmantech/reagent-toolbox#1]
hi,

Was looking for a ClojureScript/Re-Frame compatible CSS frameworks but it seems there's not so much around beside re-com. This project looks interesting. I tried to render a basic button component and it receives autogenerated class names in the dom, a react-toolbox design concept. I am wondering how do you plan to support the sass/css theming support.

**Comment by pupeno** [comment]
To be honest, I haven't looked at the theming side of things. You can include the CSS from react-toolbox if you are using sass:

https://github.com/dashmantech/reagent-toolbox-docs/blob/master/src/assets/reagent-toolbox-docs.scss#L2

**Comment by joerupen** [comment]
Thanks for the link. Wasn't aware that there's another git repo with the docs for reagent-toolbox. Quick question: how do I include the css from the link you mentioned? I mean how does sass resolve the 2 import statements 

```
@import "cljsjs/react-toolbox/development/react-toolbox.inc";
@import "cljsjs/codemirror/development/codemirror";

```

**Comment by pupeno** [comment]
You need to configure sass4clj like this:

https://github.com/dashmantech/reagent-toolbox-docs/blob/master/project.clj#L43-L45

and obviously install it to your project like this:

https://github.com/dashmantech/reagent-toolbox-docs/blob/master/project.clj#L26

and then you can run lein sass4clj once to compile it once or lein sass4clj auto to keep on compiling them on every change. The result is a css file you can include in your index.html:

https://github.com/dashmantech/reagent-toolbox-docs/blob/master/resources/public/index.html#L6

**Comment by pupeno** [comment]
Does that help?

**Comment by joerupen** [comment]
yes, thanks.
